spring:
  datasource:
    dbcp2:
      driver-class-name: arg.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/
    username: #
    password: #

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        show_sql: true

  flyway:
    enabled: true

logging:
  level:
    org:
      springframework:
        web: debug
